### ISSUE TITLE
短編が表示できない

### ISSUE THREAD

**Issue by ghost** [59naga/narou.berabou.me#1]
あまり需要はないかもしれませんが、短編だと ncode/1/が見つからないというエラーになってしまいます。

**Comment by 59naga** [comment]
確かに。`http://ncode.syosetu.com/n0831bs/`などを入力するとエラーになりますね。
これは長編の目次ページを入力すると、自動で`/1`を付け足して、１ページ目を読めるようにするための処理なのですが、これが逆に短編では弊害のようです。

**今後は、自動で`/1`を付け足さないようにし**、ページが存在しない場合は「小説ページURLを入力して下さい」というエラー表示するようにしてみて、対応しようと思います。

ご報告ありがとうございました。今後も`narou.berabou.me`をよろしくお願いします。

**Comment by 59naga** [comment]
対応してみました、下記のように閲覧できるはずです。

![2016-01-13 03 11 08](https://cloud.githubusercontent.com/assets/1548478/12272338/576ae0d2-b9a3-11e5-8d10-1fdbe5cf7f1d.png)
